USE `stock_canvas`;
DROP procedure IF EXISTS `PAYMENT_DETAIL_ADVANCE_delete`;
DELIMITER $$
USE `stock_canvas`$$
CREATE PROCEDURE `stock_canvas`.`PAYMENT_DETAIL_ADVANCE_delete` (IN p_id BIGINT)
BEGIN
	DELETE FROM `PAYMENT_DETAIL_ADVANCE` 
	WHERE `id`=p_id;
END$$
DELIMITER ;