USE `stock_canvas`;
DROP procedure IF EXISTS `PAYMENT_DETAIL_PURCHASE_ORDER_delete`;
DELIMITER $$
USE `stock_canvas`$$
CREATE PROCEDURE `stock_canvas`.`PAYMENT_DETAIL_PURCHASE_ORDER_delete` (IN p_id BIGINT)
BEGIN
	DELETE FROM `PAYMENT_DETAIL_CLIENT_ORDER` 
	WHERE `id`=p_id;
END$$
DELIMITER ;